# Generated by Django 4.2.17 on 2025-01-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pro',
            fields=[
                ('us', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('pic', models.IntegerField()),
                ('pp', models.CharField(max_length=255)),
                ('clg', models.CharField(max_length=255)),
                ('rt', models.IntegerField()),
            ],
            options={
                'db_table': 'prop',
            },
        ),
        migrations.CreateModel(
            name='sig',
            fields=[
                ('us', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('fn', models.CharField(max_length=255)),
                ('ln', models.CharField(max_length=255)),
                ('cn', models.IntegerField()),
            ],
            options={
                'db_table': 'signin',
            },
        ),
    ]
